version: '3.7'

services:
  league-board-backend:
    container_name: league-board-backend
    build:
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    stdin_open: true
    tty: true
